apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: bitcoincash-ingress
  namespace: default
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - www.bitcoincash.org
    - bitcoincash.org
    secretName: bitcoincash-tls
  backend:
    serviceName: bitcoincash
    servicePort: 84
  rules:
  - host: bitcoincash.org
    http:
      paths:
      - path: /
        backend:
          serviceName: bitcoincash
          servicePort: 84
  - host: www.bitcoincash.org
    http:
      paths:
      - path: /
        backend:
          serviceName: bitcoincash
          servicePort: 84
